import type { Metadata } from "next";
import { Prompt, Potta_One } from "next/font/google";
import "./globals.css";

const prompt = Prompt({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});
const pottaOne = Potta_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-potta"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${prompt.className} ${pottaOne.variable} antialiased`}>{children}</body>
    </html>
  );
}
